@server = https://legendary-space-umbrella-pxqqj4p5q47frjvj-8080.app.github.dev/
@ugeles = {{server}}/api/ugeles
@colegios = {{server}}/api/colegios
###
GET {{ugeles}}/1
###
POST {{ugeles}}
Content-Type: application/json

{
  "nombre" : "Ugel 03",
}
###
GET {{colegios}}
###
GET {{colegios}}/1
###
PATCH {{colegios}}/1
Content-Type: application/json

{
  "nombre" : "Maria Auxiliadora",
  "direccion" : "Av Proceres"
}
###
GET {{server}}/api/alumnos/1
###
GET {{server}}/api/alumnoslists
###
GET {{server}}/api/alumnos/1/formacion